var tarotKeywords = module.exports = {
  "maj00": ["Starting an adventure","Guidance through faith"],
  "maj01": ["Creativity","Conscious activity"],
  "maj02": ["Intuition","Meditation"],
  "maj03": ["Control issues","Motherly or feminine figure","Creatively manifesting needs","Fertility and sexuality"],
  "maj04": ["Authority situations","Rules and regulations","Fatherly or superior figure"],
  "maj05": ["Established or institutional knowledge","Desire to learn"],
  "maj06": ["Partnership","Coupling"],
  "maj07": ["Travel","Victory"],
  "maj08": ["Taming ego / animal nature","Control over fears","Discipline and willpower","Long-term commitment"],
  "maj09": ["Solitude","Honesty"],
  "maj10": ["Leaving fate to chance","Uncertainty"],
  "maj11": ["Legal matters","External balance","Consequences of actions"],
  "maj12": ["Reversal","Stasis"],
  "maj13": ["Transformation","Reconstruction"],
  "maj14": ["Moderation","Health","Temperance"],
  "maj15": ["Bondage","Addiction","Materialism"],
  "maj16": ["Upheaval","Shakeup"],
  "maj17": ["Reminder of hope","Inspiration from around","Union with spirit guide"],
  "maj18": ["Mystery","Imaginings"],
  "maj19": ["Illumination","Radiance","Vitality"],
  "maj20": ["Accountability","Rebirth","Judgment"],
  "maj21": ["Fulfillment of challenges","Revisiting an issue", "Special knowledge"],
  "cups01": ["New beginnings","Romantic possibility","Replenishment","Warnings against rushing romance"],
  "cups02": ["Romance","Attraction"],
  "cups03": ["Companionship","Festivity"],
  "cups04": ["Withdrawal","Apathy"],
  "cups05": ["Sorrow","Loss"],
  "cups06": ["Innocence","Generosity"],
  "cups07": ["Multiple options","Possible deceit"],
  "cups08": ["Departure","Abandon"],
  "cups09": ["Contentment","Conceit"],
  "cups10": ["Fulfillment","Harmony"],
  "cups11": ["Insecure of own talents","Hesitance to share feelings","Sharing gifts with world"],
  "cups12": ["Following the heart","Moving away from insecurity"],
  "cups13": ["Strong, intuitive woman","Woman with past sadness","Warnings against emotional drive"],
  "cups14": ["Someone with deep feelings","Trying to share emotions"],
  "pents01": ["Upcoming work opportunities","Material needs"],
  "pents02": ["Flow","Equilibrium","Coordination"],
  "pents03": ["Planning through teamwork","Complementarities"],
  "pents04": ["Restraint","Calculation"],
  "pents05": ["Hardship","Refuge"],
  "pents06": ["Balanced charity","Distribution"],
  "pents07": ["Harvest","Respite"],
  "pents08": ["Diligence","Persistence"],
  "pents09": ["Elegance","Self-reliance"],
  "pents10": ["Wealth","Stability"],
  "pents11": ["Brink of new beginning","Uncertainty of plans","Possible new offer","Unsure of accepting offers"],
  "pents12": ["News of money","Direction toward new job","Long-term, stable relationship"],
  "pents13": ["Natural abundance","Connection with nature","Material wealth and prosperity",],
  "pents14": ["Reliability to grow from","Necessary security","Foundation","Earth energy"],
  "swords01": ["New clarity","Sudden intuition / idea","Cutting down to truth","Clear communication in relationships"],
  "swords02": ["Blockage","Stagnancy"],
  "swords03": ["Heartbreak","Betrayal"],
  "swords04": ["Rest","Contemplation"],
  "swords05": ["Self-interest","Confrontation and conflict","Social cost and compromise"],
  "swords06": ["Journey","Sunkenness"],
  "swords07": ["Furtive","Stealth","Crafty strategy"],
  "swords08": ["Impotence","Sense of powerlessness","Blinding oneself"],
  "swords09": ["Anxiety","Restlessness","Self-agitation"],
  "swords10": ["Defeat","Collapse","Victim mentality"],
  "swords11": ["Determination","Eagerness","Warnings against rushed starts"],
  "swords12": ["Momentum toward new ideas","Youthful, innovative messenger","Advancing with determination / purpose"],
  "swords13": ["Sharp words and mind","Mind-heart communication","Analytic, practical problem-solving"],
  "swords14": ["Sharp or difficult communication","Guidance without harsh rule","Possessions above other needs"],
  "wands01": ["New purification","Change of perspective","Release from destructive influence"],
  "wands02": ["Power","Ambition"],
  "wands03": ["Adventure","Exploration"],
  "wands04": ["Celebration","Fulfillment"],
  "wands05": ["Discord","Rivalry","Competition"],
  "wands06": ["Triumph","Homecoming"],
  "wands07": ["Defiance","Assertion"],
  "wands08": ["Quick action","Decision"],
  "wands09": ["Perseverance","Determination"],
  "wands10": ["Burden","Exhaustion"],
  "wands11": ["Using strengths amidst scarcity","Resourcefulness","Choosing / acting within limitations"],
  "wands12": ["Momentum toward inner feelings","Enthusiasm","Youthful excitement","Adventure or real travel"],
  "wands13": ["Fiery passion","Intellect","Independent thinking and creativity"],
  "wands14": ["Sovereignty over own reality","Looking outside from peers","Independent / innovative thinker","Unique perspective"]
};
